// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.19.4
// source: proto/v1beta1/pets/pets_api.proto

package pets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetPetRequest defines the request for fetching a pet by ID from a database of pets.
type GetPetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Breed string `protobuf:"bytes,2,opt,name=breed,proto3" json:"breed,omitempty"`
}

func (x *GetPetRequest) Reset() {
	*x = GetPetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1beta1_pets_pets_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetRequest) ProtoMessage() {}

func (x *GetPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1beta1_pets_pets_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetRequest.ProtoReflect.Descriptor instead.
func (*GetPetRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1beta1_pets_pets_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetPetRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetPetRequest) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

// GetPetResponse defines the response for fetching a pet by ID from a database of pets.
type GetPetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pet         *Pet                   `protobuf:"bytes,1,opt,name=pet,proto3" json:"pet,omitempty"`
	LastUpdated *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
}

func (x *GetPetResponse) Reset() {
	*x = GetPetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1beta1_pets_pets_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetResponse) ProtoMessage() {}

func (x *GetPetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1beta1_pets_pets_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetResponse.ProtoReflect.Descriptor instead.
func (*GetPetResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1beta1_pets_pets_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetPetResponse) GetPet() *Pet {
	if x != nil {
		return x.Pet
	}
	return nil
}

func (x *GetPetResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// GetPetRequest defines the request for fetching all pets from a database of pets.
type GetPetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPetsRequest) Reset() {
	*x = GetPetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1beta1_pets_pets_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetsRequest) ProtoMessage() {}

func (x *GetPetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1beta1_pets_pets_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetsRequest.ProtoReflect.Descriptor instead.
func (*GetPetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1beta1_pets_pets_api_proto_rawDescGZIP(), []int{2}
}

// GetPetsResponse defines the response for fetching all pets from a database of pets.
type GetPetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pet []*Pet `protobuf:"bytes,1,rep,name=pet,proto3" json:"pet,omitempty"` // array!
}

func (x *GetPetsResponse) Reset() {
	*x = GetPetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1beta1_pets_pets_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetsResponse) ProtoMessage() {}

func (x *GetPetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1beta1_pets_pets_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetsResponse.ProtoReflect.Descriptor instead.
func (*GetPetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1beta1_pets_pets_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetPetsResponse) GetPet() []*Pet {
	if x != nil {
		return x.Pet
	}
	return nil
}

// Pet defines ...
type Pet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Breed string `protobuf:"bytes,3,opt,name=breed,proto3" json:"breed,omitempty"`
	Risk  int32  `protobuf:"varint,4,opt,name=risk,proto3" json:"risk,omitempty"`
}

func (x *Pet) Reset() {
	*x = Pet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1beta1_pets_pets_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pet) ProtoMessage() {}

func (x *Pet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1beta1_pets_pets_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pet.ProtoReflect.Descriptor instead.
func (*Pet) Descriptor() ([]byte, []int) {
	return file_proto_v1beta1_pets_pets_api_proto_rawDescGZIP(), []int{4}
}

func (x *Pet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pet) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Pet) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *Pet) GetRisk() int32 {
	if x != nil {
		return x.Risk
	}
	return 0
}

type AddPetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Breed string `protobuf:"bytes,2,opt,name=breed,proto3" json:"breed,omitempty"`
	Risk  int32  `protobuf:"varint,3,opt,name=risk,proto3" json:"risk,omitempty"`
}

func (x *AddPetRequest) Reset() {
	*x = AddPetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1beta1_pets_pets_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPetRequest) ProtoMessage() {}

func (x *AddPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1beta1_pets_pets_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPetRequest.ProtoReflect.Descriptor instead.
func (*AddPetRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1beta1_pets_pets_api_proto_rawDescGZIP(), []int{5}
}

func (x *AddPetRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddPetRequest) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *AddPetRequest) GetRisk() int32 {
	if x != nil {
		return x.Risk
	}
	return 0
}

type AddPetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddPetResponse) Reset() {
	*x = AddPetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1beta1_pets_pets_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPetResponse) ProtoMessage() {}

func (x *AddPetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1beta1_pets_pets_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPetResponse.ProtoReflect.Descriptor instead.
func (*AddPetResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1beta1_pets_pets_api_proto_rawDescGZIP(), []int{6}
}

var File_proto_v1beta1_pets_pets_api_proto protoreflect.FileDescriptor

var file_proto_v1beta1_pets_pets_api_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f,
	0x70, 0x65, 0x74, 0x73, 0x2f, 0x70, 0x65, 0x74, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x65, 0x74, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x50, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x62, 0x72, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x62, 0x72, 0x65, 0x65, 0x64, 0x22, 0x6c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x03, 0x70, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x65, 0x74, 0x73, 0x2e, 0x50, 0x65, 0x74, 0x52,
	0x03, 0x70, 0x65, 0x74, 0x12, 0x3d, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x65, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x03, 0x70, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x65, 0x74, 0x73, 0x2e, 0x50, 0x65, 0x74,
	0x52, 0x03, 0x70, 0x65, 0x74, 0x22, 0x53, 0x0a, 0x03, 0x50, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x62, 0x72, 0x65, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x69, 0x73, 0x6b, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x69, 0x73, 0x6b, 0x22, 0x4d, 0x0a, 0x0d, 0x41, 0x64,
	0x64, 0x50, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x62, 0x72, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x62, 0x72, 0x65, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x69, 0x73, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x69, 0x73, 0x6b, 0x22, 0x10, 0x0a, 0x0e, 0x41, 0x64, 0x64,
	0x50, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb1, 0x01, 0x0a, 0x07,
	0x50, 0x65, 0x74, 0x73, 0x41, 0x50, 0x49, 0x12, 0x35, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x50, 0x65,
	0x74, 0x12, 0x13, 0x2e, 0x70, 0x65, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x65, 0x74, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x50, 0x65, 0x74, 0x73, 0x12, 0x14, 0x2e, 0x70, 0x65, 0x74, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x70, 0x65, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x50,
	0x65, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x65, 0x74, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x65, 0x74, 0x73, 0x2e, 0x41,
	0x64, 0x64, 0x50, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x77,
	0x65, 0x72, 0x74, 0x79, 0x70, 0x34, 0x6e, 0x74, 0x73, 0x2f, 0x70, 0x65, 0x74, 0x73, 0x2d, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x2f, 0x70, 0x65, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v1beta1_pets_pets_api_proto_rawDescOnce sync.Once
	file_proto_v1beta1_pets_pets_api_proto_rawDescData = file_proto_v1beta1_pets_pets_api_proto_rawDesc
)

func file_proto_v1beta1_pets_pets_api_proto_rawDescGZIP() []byte {
	file_proto_v1beta1_pets_pets_api_proto_rawDescOnce.Do(func() {
		file_proto_v1beta1_pets_pets_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1beta1_pets_pets_api_proto_rawDescData)
	})
	return file_proto_v1beta1_pets_pets_api_proto_rawDescData
}

var file_proto_v1beta1_pets_pets_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_v1beta1_pets_pets_api_proto_goTypes = []interface{}{
	(*GetPetRequest)(nil),         // 0: pets.GetPetRequest
	(*GetPetResponse)(nil),        // 1: pets.GetPetResponse
	(*GetPetsRequest)(nil),        // 2: pets.GetPetsRequest
	(*GetPetsResponse)(nil),       // 3: pets.GetPetsResponse
	(*Pet)(nil),                   // 4: pets.Pet
	(*AddPetRequest)(nil),         // 5: pets.AddPetRequest
	(*AddPetResponse)(nil),        // 6: pets.AddPetResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_v1beta1_pets_pets_api_proto_depIdxs = []int32{
	4, // 0: pets.GetPetResponse.pet:type_name -> pets.Pet
	7, // 1: pets.GetPetResponse.last_updated:type_name -> google.protobuf.Timestamp
	4, // 2: pets.GetPetsResponse.pet:type_name -> pets.Pet
	0, // 3: pets.PetsAPI.GetPet:input_type -> pets.GetPetRequest
	2, // 4: pets.PetsAPI.GetPets:input_type -> pets.GetPetsRequest
	5, // 5: pets.PetsAPI.AddPet:input_type -> pets.AddPetRequest
	1, // 6: pets.PetsAPI.GetPet:output_type -> pets.GetPetResponse
	3, // 7: pets.PetsAPI.GetPets:output_type -> pets.GetPetsResponse
	6, // 8: pets.PetsAPI.AddPet:output_type -> pets.AddPetResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v1beta1_pets_pets_api_proto_init() }
func file_proto_v1beta1_pets_pets_api_proto_init() {
	if File_proto_v1beta1_pets_pets_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_v1beta1_pets_pets_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1beta1_pets_pets_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1beta1_pets_pets_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1beta1_pets_pets_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1beta1_pets_pets_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1beta1_pets_pets_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1beta1_pets_pets_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1beta1_pets_pets_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1beta1_pets_pets_api_proto_goTypes,
		DependencyIndexes: file_proto_v1beta1_pets_pets_api_proto_depIdxs,
		MessageInfos:      file_proto_v1beta1_pets_pets_api_proto_msgTypes,
	}.Build()
	File_proto_v1beta1_pets_pets_api_proto = out.File
	file_proto_v1beta1_pets_pets_api_proto_rawDesc = nil
	file_proto_v1beta1_pets_pets_api_proto_goTypes = nil
	file_proto_v1beta1_pets_pets_api_proto_depIdxs = nil
}
